global:
  scrape_interval: 15s  # Por padrão, coleta as métricas a cada 15 segundos.
  evaluation_interval: 15s  # Avalia regras a cada 15 segundos.

  # Anexa essas etiquetas a todas as séries temporais coletadas por esta instância do Prometheus.
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080', 'localhost:8081']
        labels:
          group: 'production'
      - targets: ['localhost:8082']
        labels:
          group: 'canary'

  - job_name: 'hostname'
    scrape_interval: 10s
    static_configs:
      - targets: ['IP-Host:9182', 'IP-Host:9182']  # Corrigido para estar em uma linha.
