global:
  scrape_interval: 15s  # Por padrão, coleta as métricas a cada 15 segundos.
  evaluation_interval: 15s  # Avalia regras a cada 15 segundos.

  # Anexa essas etiquetas a todas as séries temporais coletadas por esta instância do Prometheus.
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:8080', 'localhost:8081']
        labels:
          group: 'production'
      - targets: ['localhost:8082']
        labels:
          group: 'canary'

  - job_name: 'servidores'
    scrape_interval: 10s
    static_configs:
      - targets: ['192.168.56.104:9182']

  # Blackbox Exporter - Monitoramento do site atacadao.com.br
  - job_name: 'blackbox'
    scrape_interval: 10s
    metrics_path: /probe
    file_sd_configs:
      - files:
        - 'targets/blackbox_targets/*.yml'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [module]
        target_label: __param_module
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Endereço do Blackbox Exporter

  # Novo job para monitorar www.atacadao.com.br
  - job_name: 'atacadao-monitoring'
    scrape_interval: 30s  # A cada 30 segundos
    metrics_path: /probe
    params:
      module: [http_2xx]  # Usamos o módulo HTTP com resposta 2xx
    static_configs:
      - targets:
        - 'http://www.atacadao.com.br'  # Alvo a ser monitorado
    relabel_configs:
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115  # Endereço do Blackbox Exporter
      - target_label: __param_module
        replacement: http_2xx  # Tipo de verificação (http com resposta 2xx)
